spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false
    username: root
    password: Dip4rudp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect