spring:
  application:
    name: cashtracker-auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false
    username: root
    password: Dip4rudp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8161/eureka/